### ISSUE TITLE
message loading bug

### ISSUE THREAD

**Issue by Nanai10a** [Growthers/Oshavery#11]
![image](https://user-images.githubusercontent.com/62282295/133925085-e9fe6e2d-844a-492f-b7cd-5c9dccf28a3d.png)

以上の画像のような症状がみられる.

## 症状

送信したメッセージがloadされた回数*(未検証)* だけ送信された**様**に見える (実際は送信されていない？)

## 手順

1. Oshaveryを開く.
2. スクロールバーを上に持ち上げ, `loading` を表示させる.
3. 下へスクロールし, 最新のメッセージを確認する.

**Comment by Yusuke4869** [comment]
再実装が決まったためClose
