### ISSUE TITLE
チャンネル画面を上にスクロールするとスクロールバーがびくんびくんする

### ISSUE THREAD

**Issue by mk-el** [Growthers/Oshavery#13]
![image](https://user-images.githubusercontent.com/82575685/133930845-f180907f-fbac-4879-9f77-bf9717ba0747.png)

画像ではわかりにくいですが、チャンネルの上部へ行くとスクロールバーがびくんびくんし、時間経過で戻ります。

**Comment by Yusuke4869** [comment]
次バージョンでこんなことが起こらないように...
